queries = {
"pgto_query": """
    DECLARE @DATAINICIO DATE = '01/01/24';
    DECLARE @DATAFIM DATE = GETDATE();
   
    WITH TMOV AS (
        SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
        FROM CorporeRM.TMOV WITH (NOLOCK)
        WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
        AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
    ),
   
    ITMMOV AS (
        SELECT IDMOV, IDPRD
        FROM CorporeRM.TITMMOV WITH (NOLOCK)
    ),
   
    DESCR_MOV AS (
        SELECT CODTMV, DESCMOV
        FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
    ),
   
    TPRD AS (
        SELECT IDPRD, NOMEFANTASIA
        FROM CorporeRM.TPRD WITH (NOLOCK)
    ),
   
    FLAN AS (
        SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
        FROM CorporeRM.FLAN WITH (NOLOCK)
    ),
   
    FLANBAIXA AS (
        SELECT IDLAN, IDXCX, CODEVENTOBAIXA
        FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
    ),
   
    FCFO AS (
        SELECT CODCFO, CGCCFO, NOMEFANTASIA
        FROM CorporeRM.FCFO WITH (NOLOCK)
    ),
   
    FLANCOMPL AS (
        SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
        FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
    ),
   
    FXCX AS (
        SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
        FROM CorporeRM.FXCX
    ),
   
    TOTAL AS (
        SELECT DISTINCT
            E.NUMERODOCUMENTO,
            CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
            CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
            CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
            E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
            E.CODDEPARTAMENTO,
            E.CODCXA,
            E.VALORORIGINAL AS 'VALOR ORIGINAL',
            E.VALOROP6 AS 'ABATIMENTO',
            E.VALORBAIXADO AS 'VALOR BAIXADO',
            H.CGCCFO AS 'CNPJ_CLIENTE',
            H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
            G.NOMEFANTASIA,
            E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
            E.HISTORICO,
            F.CODEVENTOBAIXA,
            C.DESCMOV,
            E.DESCSTATUSCNAB AS 'STATUS CNAB',
            I.CC001 AS 'HISTÓRICO DE COBRANÇA',
            J.VALOR AS 'VALOR DO EXTRATO',
            J.CODCXA AS 'CONTA CAIXA',
            J.IDXCX AS 'REF. EXTRATO DE CAIXA'
        FROM TMOV A
        INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
        LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
        LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
        LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
        LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
        LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
        LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
        WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' AND G.NOMEFANTASIA NOT LIKE '%GETNET%' AND E.Descricao_Tipo_Pagamento NOT LIKE 'GetNet Auttar%'
    )
   
    , PGTO AS (
        SELECT
            [TIPO PAGAMENTO] AS 'TIPO PAGAMENTO',
            COUNT(*) AS 'QUANTIDADE',
            SUM([VALOR ORIGINAL]) AS 'VALOR ORIGINAL TOTAL'
        FROM TOTAL
        GROUP BY [TIPO PAGAMENTO]
    )
   
    SELECT * FROM PGTO
    ORDER BY [VALOR ORIGINAL TOTAL] DESC
    """,
"dpto_query": """
DECLARE @DATAINICIO DATE = '01/01/24';
DECLARE @DATAFIM DATE = GETDATE();

WITH TMOV AS (
    SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
    FROM CorporeRM.TMOV WITH (NOLOCK)
    WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
      AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
),
ITMMOV AS (
    SELECT IDMOV, IDPRD
    FROM CorporeRM.TITMMOV WITH (NOLOCK)
),
DESCR_MOV AS (
    SELECT CODTMV, DESCMOV
    FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
),
TPRD AS (
    SELECT IDPRD, NOMEFANTASIA
    FROM CorporeRM.TPRD WITH (NOLOCK)
),
FLAN AS (
    SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
    FROM CorporeRM.FLAN WITH (NOLOCK)
),
FLANBAIXA AS (
    SELECT IDLAN, IDXCX, CODEVENTOBAIXA
    FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
),
FCFO AS (
    SELECT CODCFO, CGCCFO, NOMEFANTASIA
    FROM CorporeRM.FCFO WITH (NOLOCK)
),
FLANCOMPL AS (
    SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA
    FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
),
FXCX AS (
    SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
    FROM CorporeRM.FXCX WITH (NOLOCK)
),
TOTAL AS (
    SELECT DISTINCT
        E.NUMERODOCUMENTO,
        CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
        CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
        CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
        E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
        E.CODDEPARTAMENTO,
        E.CODCXA,
        E.VALORORIGINAL AS 'VALOR ORIGINAL',
        E.VALOROP6 AS 'ABATIMENTO',
        E.VALORBAIXADO AS 'VALOR BAIXADO',
        H.CGCCFO AS 'CNPJ_CLIENTE',
        H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
        G.NOMEFANTASIA,
        E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
        E.HISTORICO,
        F.CODEVENTOBAIXA,
        C.DESCMOV,
        E.DESCSTATUSCNAB AS 'STATUS CNAB',
        I.CC001 AS 'HISTÓRICO DE COBRANÇA',
        J.VALOR AS 'VALOR DO EXTRATO',
        J.CODCXA AS 'CONTA CAIXA',
        J.IDXCX AS 'REF. EXTRATO DE CAIXA'
    FROM TMOV A
    INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
    LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
    LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
    LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
    LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
    LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
    LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
    WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' AND G.NOMEFANTASIA NOT LIKE '%GETNET%' AND E.Descricao_Tipo_Pagamento NOT LIKE 'GetNet Auttar%'
),

DPTO AS (
    SELECT
        B.NOME AS 'NOME',
        COUNT(*) AS 'QUANTIDADE',
        SUM([VALOR ORIGINAL]) AS 'VALOR ORIGINAL TOTAL'
    FROM TOTAL A
    INNER JOIN CorporeRM.GDEPTO B
      ON A.CODDEPARTAMENTO COLLATE Latin1_General_CI_AS = B.CODDEPARTAMENTO
    WHERE B.CODFILIAL = '1'
    GROUP BY B.NOME
)
SELECT * FROM DPTO
ORDER BY [VALOR ORIGINAL TOTAL] DESC;
""",
"ano_query": """
DECLARE @DATAINICIO DATE = '01/01/24';
DECLARE @DATAFIM DATE = GETDATE();

WITH TMOV AS (
    SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
    FROM CorporeRM.TMOV WITH (NOLOCK)
    WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
    AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
),

ITMMOV AS (
    SELECT IDMOV, IDPRD
    FROM CorporeRM.TITMMOV WITH (NOLOCK)
),

DESCR_MOV AS (
    SELECT CODTMV, DESCMOV
    FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
),

TPRD AS (
    SELECT IDPRD, NOMEFANTASIA
    FROM CorporeRM.TPRD WITH (NOLOCK)
),

FLAN AS (
    SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
    FROM CorporeRM.FLAN WITH (NOLOCK)
),

FLANBAIXA AS (
    SELECT IDLAN, IDXCX, CODEVENTOBAIXA
    FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
),

FCFO AS (
    SELECT CODCFO, CGCCFO, NOMEFANTASIA
    FROM CorporeRM.FCFO WITH (NOLOCK)
),

FLANCOMPL AS (
    SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
    FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
),

FXCX AS (
    SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
    FROM CorporeRM.FXCX
),

TOTAL AS (
    SELECT DISTINCT
        E.NUMERODOCUMENTO,
        CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
        CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
        CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
        E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
        E.CODDEPARTAMENTO,
        E.CODCXA,
        E.VALORORIGINAL AS 'VALOR ORIGINAL',
        E.VALOROP6 AS 'ABATIMENTO',
        E.VALORBAIXADO AS 'VALOR BAIXADO',
        H.CGCCFO AS 'CNPJ_CLIENTE',
        H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
        G.NOMEFANTASIA,
        E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
        E.HISTORICO,
        F.CODEVENTOBAIXA,
        C.DESCMOV,
        E.DESCSTATUSCNAB AS 'STATUS CNAB',
        I.CC001 AS 'HISTÓRICO DE COBRANÇA',
        J.VALOR AS 'VALOR DO EXTRATO',
        J.CODCXA AS 'CONTA CAIXA',
        J.IDXCX AS 'REF. EXTRATO DE CAIXA'
    FROM TMOV A
    INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
    LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
    LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
    LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
    LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
    LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
    LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
    WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' 
        AND G.NOMEFANTASIA NOT LIKE '%GETNET%' 
        AND E.Descricao_Tipo_Pagamento NOT LIKE 'GetNet Auttar%'
)

, ANO AS (
    SELECT 
        FORMAT(CONVERT(DATE, [DATA VENCIMENTO], 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO',
        COUNT(*) AS 'QUANTIDADE',
        SUM([VALOR ORIGINAL]) AS 'VALOR ORIGINAL TOTAL'
    FROM TOTAL
    GROUP BY 
        FORMAT(CONVERT(DATE, [DATA VENCIMENTO], 103), 'MM-yy', 'pt-BR')
)

SELECT [MÊS-ANO], QUANTIDADE, [VALOR ORIGINAL TOTAL]
FROM ANO
ORDER BY [MÊS-ANO] ASC""",
"total_query": """ 
DECLARE @DATAINICIO DATE = '01/01/24';
    DECLARE @DATAFIM DATE = GETDATE();
    
    WITH TMOV AS (
        SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
        FROM CorporeRM.TMOV WITH (NOLOCK)
        WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
        AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
    ),
    
    ITMMOV AS (
        SELECT IDMOV, IDPRD
        FROM CorporeRM.TITMMOV WITH (NOLOCK)
    ),
    
    DESCR_MOV AS (
        SELECT CODTMV, DESCMOV
        FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
    ),
    
    TPRD AS (
        SELECT IDPRD, NOMEFANTASIA
        FROM CorporeRM.TPRD WITH (NOLOCK)
    ),
    
    FLAN AS (
        SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
        FROM CorporeRM.FLAN WITH (NOLOCK)
    ),
    
    FLANBAIXA AS (
        SELECT IDLAN, IDXCX, CODEVENTOBAIXA
        FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
    ),
    
    FCFO AS (
        SELECT CODCFO, CGCCFO, NOMEFANTASIA
        FROM CorporeRM.FCFO WITH (NOLOCK)
    ),
    
    FLANCOMPL AS (
        SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
        FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
    ),
    
    FXCX AS (
        SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
        FROM CorporeRM.FXCX
    ),
    
    TOTAL AS (
        SELECT DISTINCT
            E.NUMERODOCUMENTO,
        CONVERT(VARCHAR(10), DATAEMISSAO, 103) AS 'DATA EMISSAO',
		FORMAT(CONVERT(DATE, A.DATAEMISSAO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO EMISSAO',
        CONVERT(VARCHAR(10), DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
		FORMAT(CONVERT(DATE, DATAVENCIMENTO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO VENCIMENTO',
        CONVERT(VARCHAR(10), DATABAIXA, 103) AS 'DATA BAIXA',
        FORMAT(CONVERT(DATE, DATABAIXA, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO BAIXA',
            E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
            E.CODDEPARTAMENTO,
            E.CODCXA,
            E.VALORORIGINAL AS 'VALOR ORIGINAL',
            E.VALOROP6 AS 'ABATIMENTO',
            E.VALORBAIXADO AS 'VALOR BAIXADO',
            H.CGCCFO AS 'CNPJ_CLIENTE',
            H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
            G.NOMEFANTASIA,
            E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
            E.HISTORICO,
            F.CODEVENTOBAIXA,
            C.DESCMOV,
            E.DESCSTATUSCNAB AS 'STATUS CNAB',
            I.CC001 AS 'HISTÓRICO DE COBRANÇA',
            J.VALOR AS 'VALOR DO EXTRATO',
            J.CODCXA AS 'CONTA CAIXA',
            J.IDXCX AS 'REF. EXTRATO DE CAIXA'
        FROM TMOV A
        INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
        LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
        LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
        LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
        LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
        LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
        LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
        WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' AND G.NOMEFANTASIA NOT LIKE '%GETNET%' AND E.Descricao_Tipo_Pagamento NOT LIKE 'GetNet Auttar%'
    )
 
 
SELECT * FROM TOTAL
""",
"reembolso_query": """
DECLARE @DATAINICIO DATE = '01/01/24';
DECLARE @DATAFIM DATE = GETDATE();

WITH TMOV AS (
    SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
    FROM CorporeRM.TMOV WITH (NOLOCK)
    WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
    AND CODTMV IN ('2.1.12')
),

ITMMOV AS (
    SELECT IDMOV, IDPRD
    FROM CorporeRM.TITMMOV WITH (NOLOCK)
),

DESCR_MOV AS (
    SELECT CODTMV, DESCMOV
    FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
),

TPRD AS (
    SELECT IDPRD, NOMEFANTASIA
    FROM CorporeRM.TPRD WITH (NOLOCK)
),

FLAN AS (
    SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
    FROM CorporeRM.FLAN WITH (NOLOCK)
),

FLANBAIXA AS (
    SELECT IDLAN, IDXCX, CODEVENTOBAIXA
    FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
),

FCFO AS (
    SELECT CODCFO, CGCCFO, NOMEFANTASIA
    FROM CorporeRM.FCFO WITH (NOLOCK)
),

FLANCOMPL AS (
    SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
    FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
),

FXCX AS (
    SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
    FROM CorporeRM.FXCX
),

_2112 AS (
    SELECT DISTINCT
        E.NUMERODOCUMENTO,
        CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
		FORMAT(CONVERT(DATE, A.DATAEMISSAO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO EMISSAO',
        CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
		FORMAT(CONVERT(DATE, E.DATAVENCIMENTO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO VENCIMENTO',
        CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
        FORMAT(CONVERT(DATE, E.DATAVENCIMENTO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO BAIXA',
        E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
        E.CODDEPARTAMENTO,
        E.CODCXA,
        E.VALORORIGINAL AS 'VALOR ORIGINAL',
        E.VALOROP6 AS 'ABATIMENTO',
        E.VALORBAIXADO AS 'VALOR BAIXADO',
        H.CGCCFO AS 'CNPJ_CLIENTE',
        H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
        G.NOMEFANTASIA,
        E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
        E.HISTORICO,
        F.CODEVENTOBAIXA,
        C.DESCMOV,
        E.DESCSTATUSCNAB AS 'STATUS CNAB',
        I.CC001 AS 'HISTÓRICO DE COBRANÇA',
        J.VALOR AS 'VALOR DO EXTRATO',
        J.CODCXA AS 'CONTA CAIXA',
        J.IDXCX AS 'REF. EXTRATO DE CAIXA'
    FROM TMOV A
    INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
    LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
    LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
    LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
    LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
    LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
    LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
    WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' 
    AND G.NOMEFANTASIA NOT LIKE '%GETNET%' 
    AND E.Descricao_Tipo_Pagamento NOT LIKE 'GetNet Auttar%'
)

SELECT * FROM _2112
""",
"parcialmente_query":"""
DECLARE @DATAINICIO DATE = '01/01/24';
DECLARE @DATAFIM DATE = GETDATE();

WITH TMOV AS (
    SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
    FROM CorporeRM.TMOV WITH (NOLOCK)
    WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
    AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
),

ITMMOV AS (
    SELECT IDMOV, IDPRD
    FROM CorporeRM.TITMMOV WITH (NOLOCK)
),

DESCR_MOV AS (
    SELECT CODTMV, DESCMOV
    FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
),

TPRD AS (
    SELECT IDPRD, NOMEFANTASIA
    FROM CorporeRM.TPRD WITH (NOLOCK)
),

FLAN AS (
    SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
    FROM CorporeRM.FLAN WITH (NOLOCK)
),

FLANBAIXA AS (
    SELECT IDLAN, IDXCX, CODEVENTOBAIXA
    FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
),

FCFO AS (
    SELECT CODCFO, CGCCFO, NOMEFANTASIA
    FROM CorporeRM.FCFO WITH (NOLOCK)
),

FLANCOMPL AS (
    SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
    FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
),

FXCX AS (
    SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
    FROM CorporeRM.FXCX
),

BAIXADO_PARCIAL AS (
    SELECT DISTINCT
        E.NUMERODOCUMENTO,
        CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
		FORMAT(CONVERT(DATE, A.DATAEMISSAO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO EMISSAO',
        CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
		FORMAT(CONVERT(DATE, E.DATAVENCIMENTO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO VENCIMENTO',
        CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
        FORMAT(CONVERT(DATE, E.DATAVENCIMENTO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO BAIXA',
        E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
        E.CODDEPARTAMENTO,
        E.CODCXA,
        E.VALORORIGINAL AS 'VALOR ORIGINAL',
        E.VALOROP6 AS 'ABATIMENTO',
        E.VALORBAIXADO AS 'VALOR BAIXADO',
        (E.VALORORIGINAL - E.VALORBAIXADO) AS 'VALOR A PAGAR',
        H.CGCCFO AS 'CNPJ_CLIENTE',
        H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
        G.NOMEFANTASIA,
        E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
        E.HISTORICO,
        F.CODEVENTOBAIXA,
        C.DESCMOV,
        E.DESCSTATUSCNAB AS 'STATUS CNAB',
        I.CC001 AS 'HISTÓRICO DE COBRANÇA',
        J.VALOR AS 'VALOR DO EXTRATO',
        J.CODCXA AS 'CONTA CAIXA',
        J.IDXCX AS 'REF. EXTRATO DE CAIXA'
    FROM TMOV A
    INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
    LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
    LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
    LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
    LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
    LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
    LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
    WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' 
    AND G.NOMEFANTASIA NOT LIKE '%GETNET%'
)

SELECT * FROM BAIXADO_PARCIAL
""",
"faculdade_query":"""
WITH FACUL AS (
    SELECT DISTINCT
        A.NUMERODOCUMENTO,
        CASE 
            WHEN A.CODTDO = '080' THEN 'MENSALIDADE' 
            WHEN A.CODTDO = '081' THEN 'MATRÍCULA' 
            WHEN A.CODTDO = '085' THEN 'ACORDO' 
            ELSE A.CODTDO  
        END AS TIPO,
        CONVERT(VARCHAR(10), DATAEMISSAO, 103) AS 'DATA EMISSAO',
		FORMAT(CONVERT(DATE, A.DATAEMISSAO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO EMISSAO',
        CONVERT(VARCHAR(10), DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
		FORMAT(CONVERT(DATE, A.DATAVENCIMENTO, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO VENCIMENTO',
        CONVERT(VARCHAR(10), A.DATABAIXA, 103) AS 'DATA BAIXA',
        FORMAT(CONVERT(DATE, A.DATABAIXA, 103), 'MM-yy', 'pt-BR') AS 'MÊS-ANO BAIXA',
        DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
        A.CODDEPARTAMENTO,
        A.CODCXA,
        A.VALORORIGINAL AS 'VALOR ORIGINAL',
        A.VALOROP6 AS 'ABATIMENTO',
        VALORBAIXADO AS 'VALOR BAIXADO',
        B.CGCCFO AS 'CNPJ_CLIENTE',
        B.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
        NULL AS NOMEFANTASIA,
        Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
        A.HISTORICO,
        C.CODEVENTOBAIXA,
        NULL AS DESCMOV,
        DESCSTATUSCNAB AS 'STATUS CNAB',
        D.CC001 AS 'HISTÓRICO DE COBRANÇA',
        E.VALOR AS 'VALOR DO EXTRATO',
        E.CODCXA AS 'CONTA CAIXA',
        E.IDXCX AS 'REF. EXTRATO DE CAIXA'
    FROM CorporeRM.FLAN A
    INNER JOIN CorporeRM.FCFO B ON A.CODCFO = B.CODCFO
    LEFT JOIN CorporeRM.FLANBAIXA C ON A.IDLAN = C.IDLAN
    LEFT JOIN CorporeRM.FLANCOMPL D ON A.IDLAN = D.IDLAN
    LEFT JOIN CorporeRM.FXCX E ON C.IDXCX = E.IDXCX
    WHERE IDMOV IS NULL 
        AND A.CODFILIAL = 61 
        AND A.DESCSTATUSLCTO NOT IN ('Baixado','CANCELADO','Baixado por Acordo') 
        AND DATAVENCIMENTO >= '01-07-2024'
)

SELECT * FROM FACUL
""",
"parcialmente_agregado":"""

 DECLARE @DATAINICIO DATE = '01/01/24';
    DECLARE @DATAFIM DATE = GETDATE();
    
    WITH TMOV AS (
        SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
        FROM CorporeRM.TMOV WITH (NOLOCK)
        WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
        AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
    ),
    
    ITMMOV AS (
        SELECT IDMOV, IDPRD
        FROM CorporeRM.TITMMOV WITH (NOLOCK)
    ),
    
    DESCR_MOV AS (
        SELECT CODTMV, DESCMOV
        FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
    ),
    
    TPRD AS (
        SELECT IDPRD, NOMEFANTASIA
        FROM CorporeRM.TPRD WITH (NOLOCK)
    ),
    
    FLAN AS (
        SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
        FROM CorporeRM.FLAN WITH (NOLOCK)
    ),
    
    FLANBAIXA AS (
        SELECT IDLAN, IDXCX, CODEVENTOBAIXA
        FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
    ),
    
    FCFO AS (
        SELECT CODCFO, CGCCFO, NOMEFANTASIA
        FROM CorporeRM.FCFO WITH (NOLOCK)
    ),
    
    FLANCOMPL AS (
        SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
        FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
    ),
    
    FXCX AS (
        SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
        FROM CorporeRM.FXCX
    ),
    
    BAIXADO_PARCIAL AS (
        SELECT DISTINCT
            E.NUMERODOCUMENTO,
            CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
            CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
            CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
            E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
            E.CODDEPARTAMENTO,
            E.CODCXA,
            E.VALORORIGINAL AS 'VALOR ORIGINAL',
            E.VALOROP6 AS 'ABATIMENTO',
            E.VALORBAIXADO AS 'VALOR BAIXADO',
			(E.VALORORIGINAL - E.VALORBAIXADO) AS 'VALOR_A_RECEBER',
            H.CGCCFO AS 'CNPJ_CLIENTE',
            H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
            G.NOMEFANTASIA,
            E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
            E.HISTORICO,
            F.CODEVENTOBAIXA,
            C.DESCMOV,
            E.DESCSTATUSCNAB AS 'STATUS CNAB',
            I.CC001 AS 'HISTÓRICO DE COBRANÇA',
            J.VALOR AS 'VALOR DO EXTRATO',
            J.CODCXA AS 'CONTA CAIXA',
            J.IDXCX AS 'REF. EXTRATO DE CAIXA'
        FROM TMOV A
        INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
        LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
        LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
        LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
        LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
        LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
        LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
        WHERE E.DESCSTATUSLCTO IN('Baixado Parcialmente') AND G.NOMEFANTASIA NOT LIKE '%GETNET%'
    )
 
 
SELECT [NOME FANTASIA CLIENTE], SUM([VALOR ORIGINAL]) AS ORIGINAL, SUM([VALOR BAIXADO]) AS BAIXADO, SUM(VALOR_A_RECEBER) AS 'A_PAGAR'
FROM BAIXADO_PARCIAL
GROUP BY [NOME FANTASIA CLIENTE]
ORDER BY 'A_PAGAR' DESC
""",
"faculdade_agregado":"""
with facul as (
SELECT DISTINCT
	A.NUMERODOCUMENTO
	,CASE WHEN A.CODTDO = '080' THEN 'MENSALIDADE' WHEN A.CODTDO = '081' THEN 'MATRÍCULA' WHEN A.CODTDO = '085' THEN 'ACORDO' ELSE A.CODTDO  END AS TIPO
	,CONVERT(VARCHAR(10), DATAEMISSAO, 103) AS 'DATA EMISSAO'
    ,CONVERT(VARCHAR(10), DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO'
    ,CONVERT(VARCHAR(10), A.DATABAIXA, 103) AS 'DATA BAIXA'
    ,DESCSTATUSLCTO AS 'STATUS LANCAMENTO'
    ,A.CODDEPARTAMENTO
    ,A.CODCXA
    ,A.VALORORIGINAL AS 'VALOR ORIGINAL'
    ,A.VALOROP6 AS 'ABATIMENTO'
    ,VALORBAIXADO AS 'VALOR BAIXADO'
	,B.CGCCFO AS 'CNPJ_CLIENTE'
	,B.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE'
	,NOMEFANTASIA = NULL
	,Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO'
	,A.HISTORICO
	,C.CODEVENTOBAIXA
	,DESCMOV = NULL
	,DESCSTATUSCNAB AS 'STATUS CNAB'
	,D.CC001 AS 'HISTÓRICO DE COBRANÇA'
    ,E.VALOR AS 'VALOR DO EXTRATO'
    ,E.CODCXA AS 'CONTA CAIXA'
    ,E.IDXCX AS 'REF. EXTRATO DE CAIXA'
	
	FROM CorporeRM.FLAN A
	INNER JOIN CorporeRM.FCFO B
	ON A.CODCFO = B.CODCFO
	LEFT JOIN CorporeRM.FLANBAIXA C
	ON A.IDLAN = C.IDLAN
	LEFT JOIN CorporeRM.FLANCOMPL D ON A.IDLAN = D.IDLAN
    LEFT JOIN CorporeRM.FXCX E ON C.IDXCX = E.IDXCX

	WHERE IDMOV IS NULL AND A.CODFILIAL = 61 AND a.DESCSTATUSLCTO NOT IN ('Baixado','CANCELADO','Baixado por Acordo') AND DATAVENCIMENTO >= '01-07-2024'

	)

	select TIPO, COUNT(TIPO) AS QUANTIDADE,SUM([VALOR ORIGINAL]) AS ORIGINAL from facul
	GROUP BY TIPO
	ORDER BY SUM([VALOR ORIGINAL]) DESC"""
}